
name: CI Calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Se configura JDK 25 (Temurin)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          check-latest: true
          cache: gradle

      - name: Asegura que gradlew es ejecutable
        run: chmod +x ./gradlew

      - name: Compilación
        run: ./gradlew compileJava

      - name: Pruebas unitarias
        run: ./gradlew test
        
      - name: Se sube el informe
        uses: actions/upload-artifact@v4
        with: 
          name: test-report 
          path: build/reports/tests/test

      - name: Cobertura de codigo
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Se sube el informe JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Fuerza comprobación de cobertura de código
        run: ./gradlew jacocoTestCoverageVerification --no-daemon
      



      
      
